/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazbasica;

import javax.swing.text.*;
import javax.swing.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class SeleccionPersonaje extends javax.swing.JFrame {

    static String Nombre;
    
    public SeleccionPersonaje() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        SeleccionClase = new javax.swing.ButtonGroup();
        GuerreroImagen = new javax.swing.JLabel();
        GuerreroText = new javax.swing.JLabel();
        GuerreroStats = new javax.swing.JLabel();
        GuerreroStats2 = new javax.swing.JLabel();
        MagoImage = new javax.swing.JLabel();
        Auxiliar = new javax.swing.JLabel();
        Mago = new javax.swing.JLabel();
        MagoStats = new javax.swing.JLabel();
        MagoStats2 = new javax.swing.JLabel();
        PicaroImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PicaroStats = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PicaroConfirm = new javax.swing.JRadioButton();
        MagoConfirm = new javax.swing.JRadioButton();
        GuerreroConfirm = new javax.swing.JRadioButton();
        Nombrar = new javax.swing.JFormattedTextField();
        FondoPergamino = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1318, 960));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GuerreroImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guerrero Vikingo.png"))); // NOI18N
        getContentPane().add(GuerreroImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 510, 350));

        GuerreroText.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        GuerreroText.setText("Guerrero");
        getContentPane().add(GuerreroText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 450, 170, 40));

        GuerreroStats.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        GuerreroStats.setText("HP: 10 ATK: 2 DEF: 2 ");
        getContentPane().add(GuerreroStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, -1, -1));

        GuerreroStats2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        GuerreroStats2.setText("SUE: 0");
        getContentPane().add(GuerreroStats2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 570, -1, -1));

        MagoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mago_1.png"))); // NOI18N
        getContentPane().add(MagoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 430, 380));

        Auxiliar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Auxiliar.setText("Nombre: ");
        getContentPane().add(Auxiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, -1, -1));

        Mago.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Mago.setText("Mago");
        getContentPane().add(Mago, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 500, -1));

        MagoStats.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        MagoStats.setText("HP: 8 ATK:3 DEF: 1");
        getContentPane().add(MagoStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 520, -1));

        MagoStats2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        MagoStats2.setText("SUE: 1");
        getContentPane().add(MagoStats2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, 520, 40));

        PicaroImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rogue.png"))); // NOI18N
        getContentPane().add(PicaroImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 330));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Picaro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 390, -1));

        PicaroStats.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        PicaroStats.setText("HP: 7 ATK: 4 DEF: 0");
        getContentPane().add(PicaroStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 520, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("SUE: 3");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 540, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 153, 0));
        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 770, 220, 80));

        SeleccionClase.add(PicaroConfirm);
        PicaroConfirm.setOpaque(false);
        getContentPane().add(PicaroConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

        SeleccionClase.add(MagoConfirm);
        MagoConfirm.setOpaque(false);
        getContentPane().add(MagoConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, -1));

        SeleccionClase.add(GuerreroConfirm);
        GuerreroConfirm.setOpaque(false);
        getContentPane().add(GuerreroConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, -1, -1));

        Nombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrarActionPerformed(evt);
            }
        });
        Nombrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombrarKeyTyped(evt);
            }
        });
        getContentPane().add(Nombrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, 190, 50));

        FondoPergamino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Tipo Petgamino.jpg"))); // NOI18N
        getContentPane().add(FondoPergamino, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(PicaroConfirm.isSelected()){
            
        }
        else if(GuerreroConfirm.isSelected()){
            
        }
        else if(MagoConfirm.isSelected()){
            
        }
        else{
            JOptionPane.showMessageDialog(null, "ERROR: Selecciona una clase!!!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrarActionPerformed
        
    }//GEN-LAST:event_NombrarActionPerformed

    private void NombrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombrarKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_NombrarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionPersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Auxiliar;
    private javax.swing.JLabel FondoPergamino;
    private javax.swing.JRadioButton GuerreroConfirm;
    private javax.swing.JLabel GuerreroImagen;
    private javax.swing.JLabel GuerreroStats;
    private javax.swing.JLabel GuerreroStats2;
    private javax.swing.JLabel GuerreroText;
    private javax.swing.JLabel Mago;
    private javax.swing.JRadioButton MagoConfirm;
    private javax.swing.JLabel MagoImage;
    private javax.swing.JLabel MagoStats;
    private javax.swing.JLabel MagoStats2;
    private javax.swing.JFormattedTextField Nombrar;
    private javax.swing.JRadioButton PicaroConfirm;
    private javax.swing.JLabel PicaroImage;
    private javax.swing.JLabel PicaroStats;
    private javax.swing.ButtonGroup SeleccionClase;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
